package principal;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author yeray
 */

public class VistaVirtual extends javax.swing.JFrame {

    
    private Graphics g;
    private int x,y;
    private List<Punto> ListaDePuntos = new ArrayList();
    private Punto punto;
    private int limiteYRecinto = 40;
    private int limiteXRecinto = 40;
    private int tampunto = 5;
    private int contadorPuntos = 0;
    private Color colorpoint = Color.red;
    /**
     * Creates new form VistaVirtual
     */
    public VistaVirtual() {
        initComponents();
    }
    
       
    public void setColorPoint(Color c){
        colorpoint = c;
    }

    public void setPoint(int x, int y, Color c){
        Punto p = new Punto((float)x,(float)y,(float)1.0,c);
        ListaDePuntos.add(p);
        contadorPuntos++;
        repaint();
    }
    @Override
    public void paint(Graphics g){
        super.paint(g);
        //recinto
        g.setColor(Color.red);
        g.drawRect(limiteXRecinto, limiteYRecinto, 640, 480);
        for(int i=0;i<ListaDePuntos.size();i++){
            punto = ListaDePuntos.get(i); 
            g.setColor(colorpoint);
            g.fillOval((int)punto.getx()+limiteXRecinto,(int)punto.gety()+limiteYRecinto,tampunto,tampunto);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTitle("Vista Virtual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
